import Navbar from '@/app/components/navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { NextAuthProvider } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // nextauth puttet rundt i layout så jeg har accesss til session i hele koden, og navbar over der resten av siden er
  return (
    <html lang="en">
      <NextAuthProvider>
        <body>
          <Navbar />
          <div className="min-h-screen bg-slate-600 text-white p-6">
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
